apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: contosoair-today
  name: contosoair-today
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair-today
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: contosoair-today
    spec:
      containers:
      - image: fabmedicalaiw.azurecr.io/contosoair-today
        name: contosoair-today
        ports:
        - containerPort: 8080
        resources: {}
status: {}
