name: Trigger auto deployment for contosoair-aca2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main-aca ]
    paths:
    - '**'
    - '.github/workflows/contosoair-aca2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca005680366bacr.azurecr.io
          username: ${{ secrets.CONTOSOAIRACA2_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTOSOAIRACA2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca005680366bacr.azurecr.io/contosoair-aca2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTOSOAIRACA2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n contosoair-aca2 -g contosoair-aca2 --server ca005680366bacr.azurecr.io --username  ${{ secrets.CONTOSOAIRACA2_REGISTRY_USERNAME }} --password ${{ secrets.CONTOSOAIRACA2_REGISTRY_PASSWORD }}
            az containerapp update -n contosoair-aca2 -g contosoair-aca2 --image ca005680366bacr.azurecr.io/contosoair-aca2:${{ github.sha }}
